name: Create distribution bundles for all components

on:
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: .
          submodules: true
          token: ${{ secrets.RUNNER_PAT }}

      - name: Bundle sub-applications
        